// This file is needed to support autocomplete for process.env
export {};

declare global {
	namespace NodeJS {
		interface ProcessEnv {
			// app base url
			NEXT_PUBLIC_APP_BASE_URL: string;

			// neon db uri
			DATABASE_URL: string;

			// better auth secret (generated by `openssl rand -hex 32`)
			BETTER_AUTH_SECRET: string;

			// github oauth client id and secret
			GITHUB_CLIENT_ID: string;
			GITHUB_CLIENT_SECRET: string;

			// google oauth client id and secret
			NEXT_PUBLIC_GOOGLE_CLIENT_ID: string;
			GOOGLE_CLIENT_SECRET: string;

			// stream video api key and secret
			NEXT_PUBLIC_STREAM_VIDEO_API_KEY: string;
			STREAM_VIDEO_API_SECRET: string;

			// stream chat api key and secret
			NEXT_PUBLIC_STREAM_CHAT_API_KEY: string;
			STREAM_CHAT_API_SECRET: string;

			// openai api key
			OPENAI_API_KEY: string;

			// polar access token
			POLAR_ACCESS_TOKEN: string;

			// uploadthing token
			UPLOADTHING_TOKEN: string;

			// verification secret (generated by `openssl rand -hex 32`)
			VERIFICATION_SECRET: string;
		}
	}
}
