import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

const inter = Inter({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Meet AI',
};

const RootLayout = ({ children }: Readonly<PropsWithChildren>) => {
	return (
		<html lang='en'>
			<body className={cn(inter.className, 'antialiased')}>{children}</body>
		</html>
	);
};

export default RootLayout;
